# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 14:12
from __future__ import unicode_literals

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0002_auto_20190321_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Picture',
            field=django_fields.fields.DefaultStaticImageField(blank=True, upload_to=''),
        ),
    ]
