# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0003_auto_20190321_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Picture',
            new_name='picture',
        ),
    ]
